name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master     
      - name: Build container and publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: radekadamczewski/rabooth-web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
